/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jframe;

import java.awt.*;
import java.awt.FlowLayout;
import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import org.jdesktop.swingx.autocomplete.*;

/**
 *
 * @author PV
 */
public class Student extends javax.swing.JPanel {
    
    DefaultTableModel model;

    /**
     * Creates new form Student
     */
    public Student() {
        initComponents();
        this.setStudentDetailToTable();
       // tbl_StudentDetails.set

    }
    
    
    public void clearTableStudentDetails(rojeru_san.complementos.RSTableMetro tbl_StudentDetails){
        DefaultTableModel model = (DefaultTableModel) tbl_StudentDetails.getModel();
        model.setRowCount(0); 
    }
    
    public void setStudentDetailToTable( ){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/library_ms", "root", "");
            java.sql.Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from student_detail where available = 'yes'");
            while(rs.next()){
                String studentId = rs.getString("student_id");
                String studentName = rs.getString("student_name");
                String major = rs.getString("major");
                String status = rs.getString("status");

                Object obj[] = {studentId, studentName, major, status};
                model = (DefaultTableModel) tbl_StudentDetails.getModel();
                model.addRow(obj);
                
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        txt_studentName = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_StudentDetails = new rojeru_san.complementos.RSTableMetro();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_BorrowHistory = new rojeru_san.complementos.RSTableMetro();

        setBackground(new java.awt.Color(102, 102, 102));
        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        setMinimumSize(new java.awt.Dimension(1200, 770));
        setPreferredSize(new java.awt.Dimension(1308, 811));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanel1.setMinimumSize(new java.awt.Dimension(1200, 770));
        jPanel1.setPreferredSize(new java.awt.Dimension(1308, 811));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setFont(new java.awt.Font("Serif", 0, 17)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Moleskine_26px.png"))); // NOI18N
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 60, 40));

        txt_studentName.setBackground(new java.awt.Color(51, 51, 51));
        txt_studentName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_studentName.setForeground(new java.awt.Color(153, 153, 153));
        txt_studentName.setText("Nhập tên bạn đọc ...");
        txt_studentName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_studentName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_studentNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_studentNameFocusLost(evt);
            }
        });
        txt_studentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_studentNameActionPerformed(evt);
            }
        });
        txt_studentName.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txt_studentNamePropertyChange(evt);
            }
        });
        txt_studentName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_studentNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_studentNameKeyTyped(evt);
            }
        });
        txt_studentName.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                txt_studentNameVetoableChange(evt);
            }
        });
        jPanel1.add(txt_studentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 310, 40));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Nhập tên sách");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 180, 40));

        tbl_StudentDetails.setBackground(new java.awt.Color(204, 204, 204));
        tbl_StudentDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên bạn đọc", "Chuyên ngành", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_StudentDetails.setColorBackgoundHead(new java.awt.Color(153, 153, 153));
        tbl_StudentDetails.setColorBordeFilas(new java.awt.Color(102, 102, 255));
        tbl_StudentDetails.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tbl_StudentDetails.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tbl_StudentDetails.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tbl_StudentDetails.setColorSelBackgound(new java.awt.Color(153, 153, 153));
        tbl_StudentDetails.setColorSelForeground(new java.awt.Color(0, 0, 0));
        tbl_StudentDetails.setFont(new java.awt.Font("Dialog", 0, 25)); // NOI18N
        tbl_StudentDetails.setFuenteFilas(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tbl_StudentDetails.setFuenteFilasSelect(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tbl_StudentDetails.setFuenteHead(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        tbl_StudentDetails.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tbl_StudentDetails.setRowHeight(40);
        tbl_StudentDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_StudentDetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_StudentDetails);
        if (tbl_StudentDetails.getColumnModel().getColumnCount() > 0) {
            tbl_StudentDetails.getColumnModel().getColumn(0).setMinWidth(100);
            tbl_StudentDetails.getColumnModel().getColumn(0).setMaxWidth(100);
            tbl_StudentDetails.getColumnModel().getColumn(3).setMinWidth(200);
            tbl_StudentDetails.getColumnModel().getColumn(3).setMaxWidth(200);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 1050, 310));

        tbl_BorrowHistory.setBackground(new java.awt.Color(204, 204, 204));
        tbl_BorrowHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên bạn đọc", "Tên sách", "Ngày mượn", "Hạn trả", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_BorrowHistory.setColorBackgoundHead(new java.awt.Color(153, 153, 153));
        tbl_BorrowHistory.setColorBordeFilas(new java.awt.Color(102, 102, 255));
        tbl_BorrowHistory.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tbl_BorrowHistory.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tbl_BorrowHistory.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tbl_BorrowHistory.setColorSelBackgound(new java.awt.Color(153, 153, 153));
        tbl_BorrowHistory.setColorSelForeground(new java.awt.Color(0, 0, 0));
        tbl_BorrowHistory.setFont(new java.awt.Font("Dialog", 0, 25)); // NOI18N
        tbl_BorrowHistory.setFuenteFilas(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tbl_BorrowHistory.setFuenteFilasSelect(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tbl_BorrowHistory.setFuenteHead(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        tbl_BorrowHistory.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tbl_BorrowHistory.setRowHeight(40);
        tbl_BorrowHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_BorrowHistoryMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_BorrowHistory);
        if (tbl_BorrowHistory.getColumnModel().getColumnCount() > 0) {
            tbl_BorrowHistory.getColumnModel().getColumn(0).setMinWidth(60);
            tbl_BorrowHistory.getColumnModel().getColumn(0).setMaxWidth(60);
            tbl_BorrowHistory.getColumnModel().getColumn(3).setMinWidth(170);
            tbl_BorrowHistory.getColumnModel().getColumn(3).setMaxWidth(170);
            tbl_BorrowHistory.getColumnModel().getColumn(4).setMinWidth(170);
            tbl_BorrowHistory.getColumnModel().getColumn(4).setMaxWidth(170);
            tbl_BorrowHistory.getColumnModel().getColumn(5).setMinWidth(170);
            tbl_BorrowHistory.getColumnModel().getColumn(5).setMaxWidth(170);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 1050, 310));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_studentNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_studentNameFocusGained
        if(txt_studentName.getText().equals("Nhập tên bạn đọc ...")){
            txt_studentName.setText("");
            txt_studentName.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_txt_studentNameFocusGained

    private void txt_studentNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_studentNameFocusLost
        if(txt_studentName.getText().equals("")){
            txt_studentName.setText("Nhập tên bạn đọc ...");
            txt_studentName.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txt_studentNameFocusLost

    private void txt_studentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_studentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_studentNameActionPerformed

    private void txt_studentNamePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txt_studentNamePropertyChange
        //        this.txt_bookId.setText(this.txt_bookName.getText());
    }//GEN-LAST:event_txt_studentNamePropertyChange

    private void txt_studentNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_studentNameKeyReleased
        try{
            this.clearTableStudentDetails(this.tbl_StudentDetails);
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/library_ms", "root", "");
            java.sql.Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from student_detail where available = 'yes' and (student_name like N'%" +
                this.txt_studentName.getText() + "%' or major like N'%" +
                this.txt_studentName.getText() + "%' or status like N'%" +
                this.txt_studentName.getText() + "%')");
            while(rs.next()){
                String studentId = rs.getString("student_id");
                String studentName = rs.getString("student_name");
                String major = rs.getString("major");
                String status = rs.getString("status");

                Object obj[] = {studentId, studentName, major, status};
                model = (DefaultTableModel) tbl_StudentDetails.getModel();
                model.addRow(obj);
                

            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_txt_studentNameKeyReleased

    private void txt_studentNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_studentNameKeyTyped

    }//GEN-LAST:event_txt_studentNameKeyTyped

    private void txt_studentNameVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_txt_studentNameVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_studentNameVetoableChange

    private void tbl_StudentDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_StudentDetailsMouseClicked
        int rowNumber = this.tbl_StudentDetails.getSelectedRow();
        TableModel model = this.tbl_StudentDetails.getModel();

        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            evt.consume();

            //            JFrame frame = new JFrame();
            //            frame.setSize(1548, 871);
            //            frame.setBackground(Color.black);
            //            frame.setOpacity(0.8f);

            int id = Integer.parseInt(model.getValueAt(rowNumber, 0).toString());
            
            try{
                this.clearTableStudentDetails(this.tbl_BorrowHistory);
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/library_ms", "root", "");
                java.sql.Statement st = con.createStatement();
                ResultSet rs = st.executeQuery("select * from borrow_book_detail where student_id like " + id
                        + " order by status asc");
                while(rs.next()){
                    String borrowId = rs.getString("id");
                    String studentName = rs.getString("student_name");
                    String bookName = rs.getString("book_name");
                    String borrowDate = rs.getString("borrow_date");
                    String dueDate = rs.getString("due_date");
                    String status = rs.getString("status");

                    Object obj[] = {borrowId, studentName, bookName, borrowDate, dueDate, status};
                    this.model = (DefaultTableModel) this.tbl_BorrowHistory.getModel();
                    this.model.addRow(obj);
                }
            } catch(Exception e){
                e.printStackTrace();
            }
            
            
        }
    }//GEN-LAST:event_tbl_StudentDetailsMouseClicked

    private void tbl_BorrowHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_BorrowHistoryMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_BorrowHistoryMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private rojeru_san.complementos.RSTableMetro tbl_BorrowHistory;
    private rojeru_san.complementos.RSTableMetro tbl_StudentDetails;
    private javax.swing.JTextField txt_studentName;
    // End of variables declaration//GEN-END:variables
}
