/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jframe;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author PV
 */
public class ViewAllRecord extends javax.swing.JFrame {

    /**
     * Creates new form ViewAllRecord
     */
    
    DefaultTableModel model;
    public ViewAllRecord() {
        initComponents();
        //setborrowBookDetailsToTable();
        search();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void clearTable() {
        DefaultTableModel model = (DefaultTableModel) tbl_issueBookDetails.getModel();
        model.setRowCount(0);
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        rSMaterialButtonCircle3 = new rojerusan.RSMaterialButtonCircle();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        year = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        day = new javax.swing.JComboBox<>();
        month = new javax.swing.JComboBox<>();
        txtBookName = new javax.swing.JTextField();
        txtLibrarian = new javax.swing.JTextField();
        txtAuthor = new javax.swing.JTextField();
        panel_table = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_issueBookDetails = new rojeru_san.complementos.RSTableMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 25)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Literature_100px_1.png"))); // NOI18N
        jLabel3.setText("Lịch sử mượn sách");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 330, 110));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, 390, 5));

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Thủ thư:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 160, 80, 40));

        rSMaterialButtonCircle3.setBackground(new java.awt.Color(102, 102, 102));
        rSMaterialButtonCircle3.setText("Tìm kiếm");
        rSMaterialButtonCircle3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle3ActionPerformed(evt);
            }
        });
        jPanel1.add(rSMaterialButtonCircle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 190, 230, 60));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel1.setText("Back");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 40));

        jPanel6.setBackground(new java.awt.Color(0, 102, 153));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("X");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 150, -1, -1));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("X");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 30));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 0, 80, 40));

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Tháng:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 90, 40));

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Năm:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 240, 80, 40));

        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NULL", "2019", "2020", "2021", "2022" }));
        jPanel1.add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 240, -1, 40));

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Ngày:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 70, 40));

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Tên sách:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 120, 40));

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Tên tác giả:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 130, 40));

        day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NULL", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel1.add(day, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, 40));

        month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NULL", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", " " }));
        jPanel1.add(month, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, -1, 40));

        txtBookName.setBackground(new java.awt.Color(0, 102, 153));
        txtBookName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtBookName.setForeground(new java.awt.Color(153, 153, 153));
        txtBookName.setText("Nhập tên sách ...");
        txtBookName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtBookName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBookNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBookNameFocusLost(evt);
            }
        });
        txtBookName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBookNameActionPerformed(evt);
            }
        });
        txtBookName.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtBookNamePropertyChange(evt);
            }
        });
        txtBookName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBookNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBookNameKeyTyped(evt);
            }
        });
        txtBookName.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                txtBookNameVetoableChange(evt);
            }
        });
        jPanel1.add(txtBookName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 210, 40));

        txtLibrarian.setBackground(new java.awt.Color(0, 102, 153));
        txtLibrarian.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtLibrarian.setForeground(new java.awt.Color(153, 153, 153));
        txtLibrarian.setText("Nhập tên thủ thư ...");
        txtLibrarian.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtLibrarian.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLibrarianFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLibrarianFocusLost(evt);
            }
        });
        txtLibrarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLibrarianActionPerformed(evt);
            }
        });
        txtLibrarian.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtLibrarianPropertyChange(evt);
            }
        });
        txtLibrarian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLibrarianKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLibrarianKeyTyped(evt);
            }
        });
        txtLibrarian.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                txtLibrarianVetoableChange(evt);
            }
        });
        jPanel1.add(txtLibrarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 160, 210, 40));

        txtAuthor.setBackground(new java.awt.Color(0, 102, 153));
        txtAuthor.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtAuthor.setForeground(new java.awt.Color(153, 153, 153));
        txtAuthor.setText("Nhập tên tác giả ...");
        txtAuthor.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtAuthor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAuthorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAuthorFocusLost(evt);
            }
        });
        txtAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAuthorActionPerformed(evt);
            }
        });
        txtAuthor.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtAuthorPropertyChange(evt);
            }
        });
        txtAuthor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAuthorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAuthorKeyTyped(evt);
            }
        });
        txtAuthor.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                txtAuthorVetoableChange(evt);
            }
        });
        jPanel1.add(txtAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 210, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1481, 330));

        panel_table.setBackground(new java.awt.Color(255, 255, 255));
        panel_table.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_issueBookDetails.setBackground(new java.awt.Color(204, 204, 204));
        tbl_issueBookDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên sách", "Tác giả", "Tên bạn đọc", "Ngày mượn", "Cho mượn", "Ngày trả", "Nhận trả", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_issueBookDetails.setColorBackgoundHead(new java.awt.Color(153, 153, 153));
        tbl_issueBookDetails.setColorBordeFilas(new java.awt.Color(102, 102, 255));
        tbl_issueBookDetails.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tbl_issueBookDetails.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tbl_issueBookDetails.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tbl_issueBookDetails.setColorSelBackgound(new java.awt.Color(153, 153, 153));
        tbl_issueBookDetails.setColorSelForeground(new java.awt.Color(0, 0, 0));
        tbl_issueBookDetails.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        tbl_issueBookDetails.setFuenteFilas(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tbl_issueBookDetails.setFuenteFilasSelect(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tbl_issueBookDetails.setFuenteHead(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        tbl_issueBookDetails.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tbl_issueBookDetails.setRowHeight(40);
        tbl_issueBookDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_issueBookDetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_issueBookDetails);
        if (tbl_issueBookDetails.getColumnModel().getColumnCount() > 0) {
            tbl_issueBookDetails.getColumnModel().getColumn(0).setMinWidth(45);
            tbl_issueBookDetails.getColumnModel().getColumn(0).setMaxWidth(45);
            tbl_issueBookDetails.getColumnModel().getColumn(4).setMinWidth(180);
            tbl_issueBookDetails.getColumnModel().getColumn(4).setMaxWidth(180);
            tbl_issueBookDetails.getColumnModel().getColumn(6).setMinWidth(180);
            tbl_issueBookDetails.getColumnModel().getColumn(6).setMaxWidth(180);
            tbl_issueBookDetails.getColumnModel().getColumn(8).setMinWidth(180);
            tbl_issueBookDetails.getColumnModel().getColumn(8).setMaxWidth(180);
        }

        panel_table.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 1390, 350));

        getContentPane().add(panel_table, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 1480, 530));

        setSize(new java.awt.Dimension(1481, 857));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void search() {
        int daySearch = 0, monthSearch = 0, yearSearch = 0;
        if (!day.getItemAt(day.getSelectedIndex()).equals("NULL")){
            daySearch = Integer.parseInt(day.getItemAt(day.getSelectedIndex()));
        }
        if (!month.getItemAt(month.getSelectedIndex()).equals("NULL")){
            monthSearch = Integer.parseInt(month.getItemAt(month.getSelectedIndex()));
        }
        if (!year.getItemAt(year.getSelectedIndex()).equals("NULL")){
            yearSearch = Integer.parseInt(year.getItemAt(year.getSelectedIndex()));
        }
        System.out.println(daySearch + " " + monthSearch + " " + yearSearch);
        String bookName = "", author = "", librarian = "";
        if (!txtBookName.getText().equals("Nhập tên sách ...")){
            bookName = txtBookName.getText().toLowerCase();
        }
        if (!txtAuthor.getText().equals("Nhập tên tác giả ...")){
            author = txtAuthor.getText().toLowerCase();
        }
        if (!txtLibrarian.getText().equals("Nhập tên thủ thư ...")){
            librarian = txtLibrarian.getText().toLowerCase();
        }
        
        
        
        try {
            Connection con = DBConnection.getConnection();
            String sql = "select id, book_name, author, student_name, return_date, borrow_date, status, borrowLibrarian, returnedLibrarian"
                    + " from borrow_book_detail\n"
                    + " where (DAY(borrow_date) = ? or (DAY(return_date) = ? or ? = 0))\n"
                    + " and (MONTH(borrow_date) = ? or (MONTH(return_date) = ? or ? = 0))\n"
                    + " and (YEAR(borrow_date) = ? or (YEAR(return_date) = ? or ? = 0))\n"
                    + " and lower(book_name) like N'%" + bookName + "%'\n"
                    + " and lower(author) like N'%" + author +"%'\n"
                    + " and (lower(borrowLibrarian) like N'%" + librarian +"%' or lower(returnedLibrarian) like N'%" + librarian + "%')\n"
                    + " order by status asc";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, daySearch); pst.setInt(2, daySearch); pst.setInt(3, daySearch);
            pst.setInt(4, monthSearch); pst.setInt(5, monthSearch); pst.setInt(6, monthSearch);
            pst.setInt(7, yearSearch); pst.setInt(8, yearSearch); pst.setInt(9, yearSearch);
//            pst.setString(13, bookName);
//            pst.setString(14, author);
//            pst.setString(15, librarian);
//            pst.setString(16, librarian);

            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                String idToTable = rs.getString("id");
                String bookNameToTable = rs.getString("book_name");
                String authorToTable = rs.getString("author");
                String studentNameToTable = rs.getString("student_name");
                String borrowDateToTable = rs.getString("borrow_date");
                String returnDateToTable = rs.getString("return_date");
                String statusToTable = rs.getString("status");
                String borrowLibrarian = rs.getString("borrowLibrarian");
                String returnLibrarian = rs.getString("returnedLibrarian");
                
                if (returnDateToTable == null) returnDateToTable = "-";
                if (returnLibrarian == null) returnLibrarian = "-";
                if (borrowLibrarian == null) borrowLibrarian = "-";

                Object[] obj = {idToTable, bookNameToTable, authorToTable, studentNameToTable, borrowDateToTable,
                    borrowLibrarian, returnDateToTable, returnLibrarian, statusToTable};
                model = (DefaultTableModel) tbl_issueBookDetails.getModel();
                model.addRow(obj);
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
        
    private void rSMaterialButtonCircle3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle3ActionPerformed
        this.clearTable();
        search();   
    }//GEN-LAST:event_rSMaterialButtonCircle3ActionPerformed
    
    
    
    private void tbl_issueBookDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_issueBookDetailsMouseClicked
        
    }//GEN-LAST:event_tbl_issueBookDetailsMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        HomePage home = new HomePage();
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jPanel6MouseClicked

    private void txtBookNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBookNameFocusGained
        if(txtBookName.getText().equals("Nhập tên sách ...")){
            txtBookName.setText("");
            txtBookName.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_txtBookNameFocusGained

    private void txtBookNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBookNameFocusLost
        if(txtBookName.getText().equals("")){
            txtBookName.setText("Nhập tên sách ...");
            txtBookName.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtBookNameFocusLost

    private void txtBookNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBookNameActionPerformed
  
    }//GEN-LAST:event_txtBookNameActionPerformed

    private void txtBookNamePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtBookNamePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBookNamePropertyChange

    private void txtBookNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBookNameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBookNameKeyReleased

    private void txtBookNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBookNameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBookNameKeyTyped

    private void txtBookNameVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_txtBookNameVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBookNameVetoableChange

    private void txtLibrarianFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLibrarianFocusGained
        if(txtLibrarian.getText().equals("Nhập tên thủ thư ...")){
            txtLibrarian.setText("");
            txtLibrarian.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_txtLibrarianFocusGained

    private void txtLibrarianFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLibrarianFocusLost
        if(txtLibrarian.getText().equals("")){
            txtLibrarian.setText("Nhập tên thủ thư ...");
            txtLibrarian.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtLibrarianFocusLost

    private void txtLibrarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLibrarianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLibrarianActionPerformed

    private void txtLibrarianPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtLibrarianPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLibrarianPropertyChange

    private void txtLibrarianKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLibrarianKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLibrarianKeyReleased

    private void txtLibrarianKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLibrarianKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLibrarianKeyTyped

    private void txtLibrarianVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_txtLibrarianVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLibrarianVetoableChange

    private void txtAuthorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAuthorFocusGained
        if(txtAuthor.getText().equals("Nhập tên tác giả ...")){
            txtAuthor.setText("");
            txtAuthor.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_txtAuthorFocusGained

    private void txtAuthorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAuthorFocusLost
        if(txtAuthor.getText().equals("")){
            txtAuthor.setText("Nhập tên tác giả ...");
            txtAuthor.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtAuthorFocusLost

    private void txtAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAuthorActionPerformed

    private void txtAuthorPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtAuthorPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAuthorPropertyChange

    private void txtAuthorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAuthorKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAuthorKeyReleased

    private void txtAuthorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAuthorKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAuthorKeyTyped

    private void txtAuthorVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_txtAuthorVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAuthorVetoableChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAllRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAllRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAllRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAllRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAllRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> day;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> month;
    private javax.swing.JPanel panel_table;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle3;
    private rojeru_san.complementos.RSTableMetro tbl_issueBookDetails;
    private javax.swing.JTextField txtAuthor;
    private javax.swing.JTextField txtBookName;
    private javax.swing.JTextField txtLibrarian;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables
}
